name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone
      run: mkdir ext && cd ext && git clone https://github.com/bresilla/pastel
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
     # run: cargo test --verbose
